MinHemsida 2/Models/Inloggning.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MinHemsida_2.Models
{
    public class Inloggning
    {
        public string Användarnamn {get; set;}

        public string Lösenord {get; set;}
    }
}

MinHemsida 2/Controllers/FilmerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MinHemsida_2.Controllers
{
    [Authorize] // Authorize har jag på alla controllers i min solution för att göra så att man måste vara inloggad för att visa mina views.
    public class FilmerController : Controller
    {
        private FilmerDBEntities db = new FilmerDBEntities();
        // GET: Filmer
        
        public ActionResult Index()
        {
            //skickar filmer till view
            List<Film> Filmlista = db.Film.ToList();
            return View(Filmlista);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        //Controllern som är kopplad till att lägga till en ny film i databasen
        public ActionResult Create(Film NyFilm)
        {
            db.Film.Add(NyFilm);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

MinHemsida 2/Controllers/FilmerDBController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MinHemsida_2.Controllers
{
    public class FilmerDBController : Controller
    {
        private FilmerDBEntities db = new FilmerDBEntities();

        // GET: FilmerDB
        public ActionResult Index()
        {
            return View(db.Film.ToList());
        }
    }
}

MinHemsida 2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MinHemsida_2.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

MinHemsida 2/Controllers/JavascriptController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MinHemsida_2.Controllers
{
    [Authorize]
    public class JavascriptController : Controller
    {
        // GET: Javascript
        public ActionResult Index()
        {
            return View();
        }
    }
}

MinHemsida 2/Controllers/JqueryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MinHemsida_2.Controllers
{
    public class JqueryController : Controller
    {
        // GET: Jquery
        public ActionResult Index()
        {
            return View();
        }
    }
}

MinHemsida 2/Controllers/KontaktController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MinHemsida_2.Controllers
{
    [Authorize]
    public class KontaktController : Controller
    {
        // GET: Kontakt
        public ActionResult Index()
        {
            return View();
        }
    }
}

MinHemsida 2/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MinHemsida_2.Controllers
{
    public class LoginController : Controller
    {
        LoginDBEntities db = new LoginDBEntities();
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]

        public ActionResult Index(Models.Inloggning Inlogg)
        {
            bool ValidUser = false;
            
            ValidUser = KollaAnvändare(Inlogg.Användarnamn, Inlogg.Lösenord); // sätter in användarnamn och lösenord in i variabeln validuser
            if (ValidUser == true)
            {
                System.Web.Security.FormsAuthentication.RedirectFromLoginPage(Inlogg.Användarnamn, false); //vid lyckad inloggning skickas användaren till startsidan.

            }
            return View();
        }

        private bool KollaAnvändare (string Användarnamn, string Lösenord) //tar emot två strings
        { // denna funktion kollar ifall inloggnings uppgifterna som ligger i databasen är samma som de som användaren har matat in
            var användare = from rader in db.Login 
                            where rader.Användarnamn.ToUpper() == Användarnamn.ToUpper() // .ToUpper gör så att användarnamnet inte är case sensitive
                            && rader.Lösenord == Lösenord
                            select rader;

            
            if (användare.Count() == 1)
            {
                //returnerar true ifall inmatningen matchade
                return true;
            }
            else
            {
                return false;
            }

        }

    }
}

MinHemsida 2/Views/Filmer/Create.cshtml
@model MinHemsida_2.Film 
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <link href="~/Style.css" rel="stylesheet" />
</head>
<body>
    <ul>
        <li>@Html.ActionLink("Startsida", "Index", "Home")</li>
        <li>@Html.ActionLink("Mina Filmer", "Index", "Filmer")</li>
        <li>@Html.ActionLink("Lägg till Filmer", "Create", "Filmer")</li>
        <li>@Html.ActionLink("Kontakt", "Index", "Kontakt")</li>
        <li>@Html.ActionLink("Jquery", "Index", "Jquery")</li>
        <li>@Html.ActionLink("Javascript", "Index", "Javascript")</li>

    </ul>
    <br />
    <h1>Lägg till filmer!</h1>
    <div id="text">
        <p>Lägg gärna till dina favorit filmer så kan du hålla koll på dem i listan!</p>
        <p>Du kommer automatiskt bli omdirigerad till din film sida när du har lagt till en film i listan.</p>
    </div>
     
    @using (Html.BeginForm())
     {
        <div id="form1">
            <div class="label">Film: </div><br /><br />
            <!--Kopplar till min Film Model och lägger till ett namn i databasen-->
            @Html.EditorFor(m => Model.Namn) <br /><br />
            <div class="label">Regissör:</div><br /><br />
            <!--Kopplar till min Film Model och lägger till en regissör i databasen-->
            @Html.EditorFor(m => Model.Regissör) <br />
            <br />

            <input id="button" type="submit" value="Lägg till" />
        </div>

     }

</body>
</html>

MinHemsida 2/Views/Filmer/Index.cshtml
@model List<MinHemsida_2.Film>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Filmer</title>
    <link href="~/Style.css" rel="stylesheet" />
</head>
<body>
    <ul>
        <li>@Html.ActionLink("Startsida", "Index", "Home")</li>
        <li>@Html.ActionLink("Mina Filmer", "Index", "Filmer")</li>
        <li>@Html.ActionLink("Lägg till Filmer", "Create", "Filmer")</li>
        <li>@Html.ActionLink("Kontakt", "Index", "Kontakt")</li>
        <li>@Html.ActionLink("Jquery", "Index", "Jquery")</li>
        <li>@Html.ActionLink("Javascript", "Index", "Javascript")</li>

    </ul>
    <br />
    <h1>Mina filmer</h1>
    <div id="text2">
        <p>Här kan du se en lista på dina filmer!</p>
        <p>För att lägga till filmer i listan klicka på "Lägg till filmer" i meny systemet. </p>
        <p>Filmerna kommer sedan att visas upp här!</p>
    </div>
    <div>
        <table>
            <tr><th>Filmens Namn</th><th>Regissör</th></tr>

            <!--Visar upp det som finns i databasen-->
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Namn)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Regissör)
                    </td>
                </tr>
            }
        </table>

    </div>
</body>
</html>

MinHemsida 2/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Startsida</title>
    <link href="~/Style.css" rel="stylesheet" />
</head>
<body>
    <ul>
        <li>@Html.ActionLink("Startsida", "Index", "Home")</li>
        <li>@Html.ActionLink("Mina Filmer", "Index", "Filmer")</li>
        <li>@Html.ActionLink("Lägg till Filmer", "Create", "Filmer")</li>
        <li>@Html.ActionLink("Kontakt", "Index", "Kontakt")</li>
        <li>@Html.ActionLink("Jquery", "Index", "Jquery")</li>
        <li>@Html.ActionLink("Javascript", "Index", "Javascript")</li>

    </ul>
    <br>


    <h1>Välkommen!</h1>
    <br />
    <br />
    <div id="text">
        <p>Detta är min första riktiga hemsida som jag har jobbat med under kursen Webbprogrammering!</p>
        <p>Hemsidan har ett par enkla funktioner som jag skulle vilja att du testar.</p>
        <p>På sidan om mina filmer kommer du kunna se en lista med filmer som du själv har valt att lägga in, kul!</p>
        <p>Jag har även lagt in två stycken funktioner med jquery och javascript.</p>
        <p>Dessa två funktioner hänger inte direkt ihop med mitt tema som jag har på sidan vilket är film</p>
        <p>Men det kan vara kul att testa dem ändå, surfa bara vidare genom meny systemet längst upp på sidan så kan du testa dessa!</p>

    </div>

</body>
</html>

MinHemsida 2/Views/Javascript/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Javascript</title>
    <link href="~/Style.css" rel="stylesheet" />
</head>
<body>
    <ul>
        <li>@Html.ActionLink("Startsida", "Index", "Home")</li>
        <li>@Html.ActionLink("Mina Filmer", "Index", "Filmer")</li>
        <li>@Html.ActionLink("Lägg till Filmer", "Create", "Filmer")</li>
        <li>@Html.ActionLink("Kontakt", "Index", "Kontakt")</li>
        <li>@Html.ActionLink("Jquery", "Index", "Jquery")</li>
        <li>@Html.ActionLink("Javascript", "Index", "Javascript")</li>

    </ul>
    <h1>Min Javascript funktion</h1>

    <div id="text">
        <p>På denna sidan kan du lägga till filmer som du vill köpa eller hyra som vi sedan lägger ihop och ger dig den totala summan.</p>
        <p>Du får även reda på ifall det tillkommer frakt beroende på priset.</p>
    </div>

    <br />
    <br />
    <br />

    <!--Inmatning kopplad till funktionen beräknaPris-->
    <form id="form1" name="myForm">
        Film 1 <input type="text" id="prisvara1" name="prisvara1"> <br><br>
        Film 2 <input type="text" id="prisvara2" name="prisvara2"> <br><br>
        Film 3 <input type="text" id="prisvara3" name="prisvara3"> <br><br>

        <button type="button" onclick="beräknaPris()">Beräkna</button>
    </form>

    <!--Här skrivs resultatet ut från funktionen beräknaPris-->
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <div id="text2">
        <div id="pris"></div>
        <div id="prismedmoms"></div>
        <div id="prisfrakt"></div>
    </div>
    
    <script>
        function beräknaPris() {
            //hämtar in värdena från inmatningen av användare genom "getElementById" och sätter in dem i en variabel
            var vara1 = document.getElementById("prisvara1").value * 1;
            var vara2 = document.getElementById("prisvara2").value * 1;
            var vara3 = document.getElementById("prisvara3").value * 1;
           

            var sum = vara1 + vara2 + vara3;

            document.getElementById("pris").innerHTML = "Pris: " + sum + " kr";

            var sumMoms = sum * 1.25;

            document.getElementById("prismedmoms").innerHTML = "Pris med Moms: " + sumMoms + " kr";

            
            if (sumMoms < 500) {
                document.getElementById("prisfrakt").innerHTML = "Pris frakt: Frakt 50:-";
                
            }
            else {
                document.getElementById("prisfrakt").innerHTML = "Frakt: Fri frakt";
                
            }

        }

    </script>

    <div>
    </div>
</body>
</html>

MinHemsida 2/Views/Jquery/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link href="~/Style.css" rel="stylesheet" />
</head>
<body>

    <ul>
        <li>@Html.ActionLink("Startsida", "Index", "Home")</li>
        <li>@Html.ActionLink("Mina Filmer", "Index", "Filmer")</li>
        <li>@Html.ActionLink("Lägg till Filmer", "Create", "Filmer")</li>
        <li>@Html.ActionLink("Kontakt", "Index", "Kontakt")</li>
        <li>@Html.ActionLink("Jquery", "Index", "Jquery")</li>
        <li>@Html.ActionLink("Javascript", "Index", "Javascript")</li>

    </ul>

    <script>
        $(document).ready(function () { // document.ready funktion gör så att funktionen väntar med att köras tills att dokumentet är färdig laddat
            $("#hide").click(function () { // här kopplar jag funktionen till min "button"
                $(".test").hide();// detta gör så att allting som är tilldelat till klassen ".test" försvinner från skärmen
            });
        });

        $(document).ready(function () { 
            $("#show").click(function () { 
                $(".test").show();// detta gör så att allting som är tilldelat till klassen ".test" visas på skärmen igen efter att det blivit borttaget
            });
        });
    </script>

    <h2 class="test">Välkommen till min jquery funktion!</h2>

    <p class="test">Detta är en mening som kommer att försvinna.</p>
    <p id="text">Denna meningen finns kvar!</p>

    <div id="form1">
        <!--Knappar som man kan klicka på som är kopplad till mitt jquery script ovanför-->
        <button type="button" id="hide">Göm texten!</button>
        <button type="button" id="show">Visa texten!</button>

    </div>
</body>
</html>

MinHemsida 2/Views/Kontakt/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Style.css" rel="stylesheet" />
</head>
<body>
    <ul>
        <li>@Html.ActionLink("Startsida", "Index", "Home")</li>
        <li>@Html.ActionLink("Mina Filmer", "Index", "Filmer")</li>
        <li>@Html.ActionLink("Lägg till Filmer", "Create", "Filmer")</li>
        <li>@Html.ActionLink("Kontakt", "Index", "Kontakt")</li>
        <li>@Html.ActionLink("Jquery", "Index", "Jquery")</li>
        <li>@Html.ActionLink("Javascript", "Index", "Javascript")</li>

    </ul>
    <div class="kontakt">

        <br />
        <br />
        <br />

        E-mail: Sihe0008@student.hv.se <br /> <br />

        Mobil: 123534543563 <br /> <br />

        Fler kontakt uppgifter kommer inom kort. <br /> <br />

        Fortsatt trevlig dag!



     

    </div>
</body>
</html>

MinHemsida 2/Views/Login/Index.cshtml
@model MinHemsida_2.Models.Inloggning
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link href="~/Style.css" rel="stylesheet" />
</head>
<body>
    
    <!--Detta är min loginform där användaren matar in sina inloggningsuppgifter-->
    @using (Html.BeginForm())
     {
        <h1>Logga in</h1>
        <div class="loginbox">
            <div class="label1">Användarnamn: </div><br /> <br />
            
            <!--Html helper som kopplar inmatningen till min Inloggnings model-->
            @Html.TextBoxFor(m => m.Användarnamn, new { @class = "input"}) <br /> <br />

            <div class="label1">Lösenord: </div><br /> <br />

            @Html.PasswordFor(m => m.Lösenord, new { @class = "input" }) <br />
            <br />

            <input class="button" type="submit" value="Logga in" />
        </div>
       
     }
</body>
</html>